In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_csv(r"C:\Users\rahul\OneDrive\Desktop\PYTHON\Loan Prediction Dataset.csv")
df.shape

(367, 12)

In [7]:
# Changing the Datatype of columns as per required
df['LoanAmount'] = pd.to_numeric(df['LoanAmount'], errors='coerce')
df['Loan_Amount_Term'] = pd.to_numeric(df['Loan_Amount_Term'], errors='coerce')
df['Dependents'] = df['Dependents'].replace('3+', 3)
df['Dependents'] = pd.to_numeric(df['Dependents'], errors='coerce')

In [9]:
df['Self_Employed'].fillna('No', inplace=True)              # Filling missing values in Self_Employed column
df['Credit_History'].fillna(df['Credit_History'].mode()[0], inplace=True)     # filling missing values with mode
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)

df['Gender'].fillna(df['Gender'].mode()[0], inplace=True) # Gender is Categorical so filling with mode value
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)

In [11]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [13]:
df.describe()

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,367.000000,367.000000,367.000000,367.000000,367.000000,367.000000
mean,0.806540,4805.599455,1569.577657,135.980926,342.822888,0.839237
std,1.065177,4910.685399,2334.232099,60.959739,64.658402,0.367814
min,0.000000,0.000000,0.000000,28.000000,6.000000,0.000000
25%,0.000000,2864.000000,0.000000,101.000000,360.000000,1.000000
50%,0.000000,3786.000000,1025.000000,125.000000,360.000000,1.000000
75%,2.000000,5060.000000,2430.500000,157.500000,360.000000,1.000000
max,3.000000,72529.000000,24000.000000,550.000000,480.000000,1.000000

In [29]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].astype(int)
df['Dependents'] = df['Dependents'].astype(int)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             367 non-null    object
 2   Married            367 non-null    object
 3   Dependents         367 non-null    int32
 4   Education          367 non-null    object
 5   Self_Employed      367 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         367 non-null    float64
 9   Loan_Amount_Term   367 non-null    int32
 10  Credit_History     367 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(2), int32(2), int64(2), object(6)
memory usage: 31.7+ KB

In [19]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360,1.0,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360,1.0,Urban

In [31]:
df.to_csv("loan_cleaned.csv", index=False)

In [27]:
df['Self_Employed'].fillna('No', inplace=True)
df['Credit_History'] = df['Credit_History'].astype(int)

In [33]:
import os
os.getcwd()

'C:\\Users\\rahul\\PYTHON'